language: java
jdk: openjdk12
install: npm install -g newman
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew run & sleep 5 && newman run docs/TODOOSE.postman_collection.json && kill %1
